.class public abstract Ljl/a$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Ljl/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Ljl/a;I)[Ljava/lang/Object;
    .locals 0

    new-instance p0, Lnj/o;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lnj/o;-><init>(Ljava/lang/String;)V

    throw p0
.end method
